### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by silvioprog** [wyhaya/see#13]
Hi.

How to generate the binaries for [releasing](https://github.com/wyhaya/see/releases)? It would be nice to release a new version containing the [last fixes](https://github.com/wyhaya/see/pull/11). 🙂

cheers

**Comment by wyhaya** [comment]
https://github.com/wyhaya/see/blob/e03dfde313b827107b98d34c18fe2a50b6917a66/.github/workflows/CICD.yml#L75-L81

Just create a new release and github `actions` will help us publish and upload the binaries.

I'll do some more work on it and release it later.

**Comment by silvioprog** [comment]
Wow, this is awesome! I didn't know this feature existed in `actions`. 😃

Thank you very much for showing it! 👍
