### ISSUE TITLE
About update

### ISSUE THREAD

**Issue by silvioprog** [wyhaya/see#14]
It would be nice to update the about area (text and topics) as following:

![image](https://user-images.githubusercontent.com/1456829/105714345-faf30e80-5efa-11eb-88a1-fa19c42f9de8.png)

This update helps to make it easy to filter and find `see` in search tools like Google, Bind, GitHub etc.

**Comment by wyhaya** [comment]
Thanks for the suggestion, but I think it's pretty good now, it's very simple and clear, I don't like too much text introduction

**Comment by silvioprog** [comment]
No problem dude. Just a tip: it would be nice to remove the article `A` from the text, making it as `Simple and fast web server`. Articles (_a_, _an_, and _the_) are not so welcome to start describing when publishing a tool in package managers like `APT` (Debian*), `Pacman` (Arch*) and `DNF` (Red Hat*).

**Comment by wyhaya** [comment]
Thanks for the suggestion, I will remove it.
