### ISSUE TITLE
[BINARY REQUEST] macos

### ISSUE THREAD

**Issue by silvioprog** [wyhaya/see#23]
If would be nice to provide binary for `macos-x86_64`, allowing the users to run `see` on Mac OS (e.g. [miniserve/releases](https://github.com/svenstaro/miniserve/releases)).

**Comment by wyhaya** [comment]
The x86_64 program running for macOS is available on the release page as ` see-x86_64-apple-darwin.zip `

**Comment by silvioprog** [comment]
Oh, I didn't see that. 😅 Thank you @wyhaya!

**Comment by silvioprog** [comment]
I have a question. What do you think about renaming the binaries for readability? For example:

`see-x86_64-apple-darwin` -> `see-macos-x86_64`
`see-x86_64-pc-windows-msvc` -> `see-windows-x86_64`
`see-x86_64-unknown-linux-gnu` -> `see-linux-x86_64`

It would avoid words like `*-unknown-*` useless for general users that just want to download `see` to their system. 🤔

**Comment by wyhaya** [comment]
This architecture + platform approach feels good to me because the naming is more precise.
