### ISSUE TITLE
Log options

### ISSUE THREAD

**Issue by ZikZakFR** [wyhaya/see#4]
I believe that the example is wrong when we want to use more than the mode.

If I follow the example then:
> log:
>   file: /var/log/www.log
>   format: ${request_path} ${header_host}

Will return:
> error: Cannot parse `mode`, It should be 'string', but found:
> BadValue

If I use:
> log:
>   mode: file
>   file: /var/log/www.log
>   format: ${request_path} ${header_host}

Then there is no error but the log doesn't change whatever I use in format.

**Comment by wyhaya** [comment]
@ZikZakFR 
Thanks for your feedback, this is just preliminary planning, I have not implemented this function yet.

**Comment by ZikZakFR** [comment]
OK, it explains why I could nto figure it out.
Another thing then, is compresison working for CSS? In my case teh page was not rendered with its stylesheet if CSS is set in the compressed extensions of the config file.

**Comment by wyhaya** [comment]
```yml
compress: true
# or
compress:
    mode: auto  # gzip / br / ...
```
> const COMPRESS_EXTENSIONS =  ["html", "css", "js", "json", "png", "jpg"]

By default, CSS will be compressed.

There is a problem with encoding data now, I will fix it as soon as possible

**Comment by ZikZakFR** [comment]
I have a config file with this:
>    compress:
>       mode: gzip
>       level: 9
>       extension:
>         - js
>         - txt
>         - html
>         - css

Actually it is not the CSS alone, if I replace it with jpg then my pictures are missing.
Then again it must be the format of my config file here.

**Comment by wyhaya** [comment]
If extension is not filled, the default value will be used.  
If any value is filled, the default configuration will be overwritten.

**Comment by wyhaya** [comment]
@ZikZakFR Compressed response has been fixed.
