### ISSUE TITLE
error: reached the type-length limit while instantiating

### ISSUE THREAD

**Issue by ZikZakFR** [wyhaya/see#5]
Hello,

"cargo b --release" ends with the error:

Compiling hyper v0.13.5
   Compiling see v0.0.1 (/home/user/see)
error: reached the type-length limit while instantiating `<std::slice::IterMut<futures_uti...]]], std::result::Result<(), !>>`
     |
     = note: consider adding a `#![type_length_limit="1205205"]` attribute to your crate

error: aborting due to previous error

error: could not compile `see`.

To learn more, run the command again with --verbose.

Then "cargo b --verbose --release":

error: could not compile `see`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name see src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=0b89b58ff303fdbc -C extra-filename=-0b89b58ff303fdbc --out-dir /home/user/see/target/release/deps -L dependency=/home/user/see/target/release/deps --extern ace=/home/user/see/target/release/deps/libace-f3edcb8d40f0e2e0.rlib --extern async_compression=/home/user/see/target/release/deps/libasync_compression-8c62e395b3313650.rlib --extern bright=/home/user/see/target/release/deps/libbright-c6253d40f58194b1.rlib --extern dirs=/home/user/see/target/release/deps/libdirs-694d139253cf792f.rlib --extern futures=/home/user/see/target/release/deps/libfutures-d73fe93c74feb37f.rlib --extern globset=/home/user/see/target/release/deps/libglobset-5f28f28735039fd8.rlib --extern hyper=/home/user/see/target/release/deps/libhyper-047609707ce0b198.rlib --extern lazy_static=/home/user/see/target/release/deps/liblazy_static-7a6a5d78b39cb3bd.rlib --extern libc=/home/user/see/target/release/deps/liblibc-d69bc1d16c59227e.rlib --extern num_cpus=/home/user/see/target/release/deps/libnum_cpus-685e32fbb90c3521.rlib --extern percent_encoding=/home/user/see/target/release/deps/libpercent_encoding-f93b4f00b32f28df.rlib --extern rand=/home/user/see/target/release/deps/librand-fb6c06ae6d7a3ef4.rlib --extern regex=/home/user/see/target/release/deps/libregex-517550e37cf62635.rlib --extern time=/home/user/see/target/release/deps/libtime-0f6dec442bc2198e.rlib --extern tokio=/home/user/see/target/release/deps/libtokio-909a21f0c0ec7910.rlib --extern tokio_rustls=/home/user/see/target/release/deps/libtokio_rustls-205535c160e25f57.rlib --extern webpki_roots=/home/user/see/target/release/deps/libwebpki_roots-730e62b779d4fb33.rlib --extern yaml_rust=/home/user/see/target/release/deps/libyaml_rust-845f3ecf8d13e17f.rlib -L native=/home/user/see/target/release/build/miniz-sys-7294c154801d7ce2/out -L native=/home/user/see/target/release/build/ring-008c1b45642b9eb4/out` (exit code: 1)

**Comment by wyhaya** [comment]
If you use ‘rustup’ please try ‘rustup update’

**Comment by ZikZakFR** [comment]
I do not. I only installed cargo with apt.
sudo apt install cargo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cargo is already the newest version (0.42.0-0ubuntu1~18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by wyhaya** [comment]
What is your rustc version？

**Comment by ZikZakFR** [comment]
rustc 1.41.0
Note that this is for an ARM platform here, if it matters.

**Comment by wyhaya** [comment]
Now that 1.43.0 has been released, this issue should be resolved after the upgrade
