### ISSUE TITLE
Upgrade the "time" library

### ISSUE THREAD

**Issue by silvioprog** [wyhaya/see#9]
It would be nice to upgrade the [`time`](https://github.com/wyhaya/see/blob/master/Cargo.toml#L32) library to `0.2.24`.

**Comment by wyhaya** [comment]
We just use Timespec in one place and it works very well so far, if we upgrade to 0.2, we will add more dependencies.

https://github.com/wyhaya/see/blob/694ed6571ff375e272df83afcc07df3ebe6f9b89/src/option/directory.rs#L135

**Comment by silvioprog** [comment]
What do you think about migrating to [chrono](https://github.com/chronotope/chrono)? 🙂 If you agree, I can try to send a new PR replacing `time` by `chrono`  keeping the `strftime()`-like formatting style.

**Comment by wyhaya** [comment]
`time 0.1` works very well so far, has very few dependencies, is very simple, and although chrono is very powerful, I don't see any need to upgrade at all.

Can you tell me why I need to upgrade time?

**Comment by silvioprog** [comment]
Because it is marked as [deprecated](https://crates.io/crates/time/0.1.44), i.e using it as own risk could introduce unwanted bugs/insecurities to the `see` tool.

**Comment by wyhaya** [comment]
Will be merged in #11
